image: 
  - Visual Studio 2019
    
version: 2.0.0.{build}

install:
  - git submodule update --init --recursive

build_script:
  - pwsh: .\build.ps1 -p wasm -xb '--target','cpp_tests','--config','Release' -xc '-DAX_ENABLE_EXT_EFFEKSEER=ON','-DAX_WASM_THREADS=0'
  - pwsh: 7z a build_wasm.zip build_wasm/bin/**/*

artifacts:
  - path: build_wasm.zip
    name: build_wasm
